### ListaUsuarios
GET localhost:8080/api/users

### Cadastra User
POST localhost:8080/api/users
Content-Type: application/json

{
  "name": "Guilherme",
  "email": "gui@email.com",
  "password": "1234",
  "role": "ADM"
}

### Cadastra User Maria
POST localhost:8080/api/users
Content-Type: application/json

{
  "name": "maria",
  "email": "maria@email.com",
  "password": "1234",
  "role": "ADM"
}

###mais um
POST localhost:8080/api/users
Content-Type: application/json

{
"name": "Roberto",
"email": "roberto@email.com",
"password": "1234"
}

### Pega pelo ID
GET localhost:8080/api/users/2

### Login
POST localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "gui@email.com",
  "password": "1234"
}
> {%
client.global.set("token", response.body.token)
client.global.set("id", response.body.user.id)
 %}

### Deleta User

DELETE localhost:8080/api/users/2
Authorization: Bearer {{token}}

### Salva Pedido
POST localhost:8080/api/pedido
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "numeropedido": 5,
  "codigoprodutos": [
    101
  ],
  "numeromesa": 5,
  "quantidade": 1,
  "codgruest": 3
}

### Lista Pedidos
GET localhost:8080/api/pedidos/1

### Cadastra Produtos
POST localhost:8080/api/produto
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "codigoProduto": 101,
  "descricao": "bujão",
  "preco": 96
}

### Lista Produtos
GET localhost:8080/api/produto/1

