### ListaUsuarios
GET localhost:8080/api/users

### Cadastra User
POST localhost:8080/api/users
Content-Type: application/json

{
  "name": "Guilherme",
  "email": "gui@email.com",
  "password": "1234",
  "role": "ADM"
}

### Cadastra User
POST localhost:8080/api/users
Content-Type: application/json

{
"name": "Roberto",
"email": "roberto@email.com",
"password": "1234"
}

### Pega User pelo ID
GET localhost:8080/api/users/2

### Login
POST localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "gui@email.com",
  "password": "1234"
}
> {%
client.global.set("token", response.body.token)
 %}

### Deleta User
DELETE localhost:8080/api/users/2
Authorization: Bearer {{token}}

### Pega os CodGruEst
GET localhost:8080/api/codgruest

### Cria os CodGruEst
POST localhost:8080/api/codgruest
Content-Type: application/json
Authorization: Bearer {{token}}

[
  {
    "codGruEst": 1,
    "descricao": "Bebidas"
  },
  {
    "codGruEst": 2,
    "descricao": "Comidas"
  },
  {
    "codGruEst": 3,
    "descricao": "Sobremesas"
  }

]

### Salva Pedido
POST localhost:8080/api/pedido
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "numeropedido": 3,
  "codigoprodutos": 303,
  "numeromesa": 10,
  "quantidade": 1,
  "codgruest": 3
}

### Lista Pedidos
GET localhost:8080/api/pedidos/1

### Cadastra Produtos
POST localhost:8080/api/produto
Content-Type: application/json
Authorization: Bearer {{token}}

[{
  "codigoProduto": 202,
  "descricao": "Batata",
  "preco": 15,
  "codGruEst": 2
},
  {
  "codigoProduto": 303,
  "descricao": "Sorvete",
  "preco": 10,
  "codGruEst": 3
},
{
  "codigoProduto": 404,
  "descricao": "Cerveja",
  "preco": 5,
  "codGruEst": 1
}, {
    "codigoProduto": 505,
    "descricao": "Hamburguer",
    "preco": 20,
    "codGruEst": 2
},
{
    "codigoProduto": 606,
    "descricao": "Refrigerante",
    "preco": 10,
    "codGruEst": 1
}]

### Atualiza Produto
PUT localhost:8080/api/produto/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "codigoProduto": 202,
  "descricao": "Batata",
  "preco": 50.50,
  "codGruEst": 1
}

### Lista Produtos
GET localhost:8080/api/produto

### Cria Mesa
POST localhost:8080/api/mesa/5
Authorization: Bearer {{token}}

### Lista Mesas
GET localhost:8080/api/mesa/pedidos/5

